Fixes to calculation to accept 0 as min val
carwow/elm-slider pull request #1
Opened 2017-11-08 09:23 UTC by nigelmansoncarwow

added plus sign and fixed calculations to allow min value to accept 0 as a value

2017-11-08 14:01 UTC, hard2hack requested changes

2017-11-08 14:01 UTC, hard2hack commented on src/DoubleSlider.elm
> +    , thumbOverlapThresold : Float
Thresold -> Threshold?

2017-11-08 14:01 UTC, hard2hack commented on src/DoubleSlider.elm
> +                            { model | lowValue = if(convertedValue > model.lowValue) then convertedValue else convertedValue + model.min }
I'd put this if/else outside this assignment

2017-11-08 14:01 UTC, hard2hack commented on src/DoubleSlider.elm
> +        (model.formatter model.lowValue) ++ " - " ++ (model.formatter model.highValue) ++ isOverMax model.overMax model.highValue model.max
put parenthesis around `(isOverMax model.overMax model.highValue model.max)`

2017-11-08 14:01 UTC, hard2hack commented on src/DoubleSlider.elm
> +    if(isOverMax && maxValue == currentHighValue) then
no need of parenthesis in the if

2017-11-08 14:01 UTC, hard2hack commented on src/DoubleSlider.elm
> +                    toString (round (((model.max / rectangle.width)) * mouseX))
too many parenthesis

2017-11-09 14:32 UTC, Zeneixe requested changes

2017-11-09 14:32 UTC, Zeneixe commented on src/DoubleSlider.elm
> +init : { min : Float, max : Float, step : Int, lowValue : Float, highValue : Float, overlapThreshold : Int, formatter : Float -> String, overMax : Bool } -> Model
I still don't know what overMax means

2017-11-09 15:48 UTC, nigelmansoncarwow commented on src/DoubleSlider.elm
> +init : { min : Float, max : Float, step : Int, lowValue : Float, highValue : Float, overlapThreshold : Int, formatter : Float -> String, overMax : Bool } -> Model
removed..

2017-11-09 16:11 UTC, Zeneixe approved these changes

2017-11-14 10:39 UTC, merged